### PR TITLE
Hacktoberfest2021 program 2

### PR DESCRIPTION
**Pull request by Flash007-alt**

### CODE REVIEW

**Comment by pravee42** [comment]
image
image

there was some bug in the code fix it
i am not gonna accept this until this fixed

**Comment by pravee42** [comment]
and also enter the issue number other this will not be accepted

**Comment by pravee42** [comment]
i hope it is a duplicate commit the was code already to check the am-strong number

- [ ] close this pull request
- [ ] send me the new code here so that i can replace it and merge
you can choose any one of the above options

**Comment by Flash007-alt** [comment]
ok , i will update the code

**Pull request closed without merging**
